### ISSUE TITLE
Change Schema error page Home link

### ISSUE THREAD

**Issue by martyndavies** [zuplo/zudoku#183]
On https://zudoku.dev/demo, the _Go back home_ link does not link to the Zudoku homepage.

**Comment by dan-lee** [comment]
Which "Go back home" link?

**Comment by martyndavies** [comment]
@dan-lee At the bottom of the schema error page. As shown here:

![CleanShot 2024-09-06 at 10 50 42](https://github.com/user-attachments/assets/80a4bd50-8b04-433b-8656-20db4ce9ea8b)

**Comment by dan-lee** [comment]
Hmm, well, yeah, it tries to go back to the base path, which in most cases is just `/` 🤔 The demo is just a special instance of Zudoku that has no multiple pages. Could we just remove that link? Not sure if it really has a practical use case anyway

**Comment by martyndavies** [comment]
Sure, I think it's fine to remove it in this case @dan-lee
