### ISSUE TITLE
Provide json / yaml as a string

### ISSUE THREAD

**Issue by majoshi1** [zuplo/zudoku#227]
As per the [API docs](https://zudoku.dev/docs/configuration/api-reference), there are 2 options: url & file. Is it possible to provide a json / yaml as a string? 

e.g.
```
const config = {
  // ...
  apis: {
    type: "string",
    input: "<String containing json / yaml>",
    navigationId: "api",
  },
  // ...
};
```

**Comment by dan-lee** [comment]
Oh, this actually should be work already. 
It's just missing the correct type; you can `@ts-ignore` the error for `APIs.type` for now and use the raw string in `input.` I PR https://github.com/zuplo/zudoku/pull/237 to address this

**Comment by dan-lee** [comment]
Released in https://github.com/zuplo/zudoku/releases/tag/v0.11.0
