### ISSUE TITLE
TypeError: fetch failed

### ISSUE THREAD

**Issue by majoshi1** [zuplo/zudoku#228]
Getting error while starting a freshly created app, behind corporate firewall. Any idea?
OS: Windows 10.
Client: Git Bash

```
$ npm create zudoku-app@latest

> npx
> create-zudoku-app

√ What is your project named? ... zudoku-app1
√ Would you like to use TypeScript? ... No
√ Would you like to use ESLint? ... Yes
Creating a new Zudoku app in c:\opt\zudoku-app1.

Using npm.

Initializing project with template: default


Installing dependencies:
- react
- react-dom
- zudoku

Installing devDependencies:
- eslint
. . .

$ cd zudoku-app1

```
Please check attached image for the error.

![image](https://github.com/user-attachments/assets/0a65cb69-896e-4d2b-929e-ee19eae67a1c)

**Comment by majoshi1** [comment]
Is it possible to update the setup to avoid accessing gitHub.com, while running the app?

**Comment by dan-lee** [comment]
@majoshi1 I just found that you can skip the outdated check with `ZUDOKU_DISABLE_UPDATE_CHECK=1`, can you try that?

https://github.com/zuplo/zudoku/blob/879f5c078f73cc56c14012368926fb0d93b914cf/packages/zudoku/src/cli/common/outdated.ts#L15-L19

**Comment by majoshi1** [comment]
That works. I think, this should be default.
