### ISSUE TITLE
Bug: light and dark logos are always displayed  

### ISSUE THREAD

**Issue by vikviksecuri** [zuplo/zudoku#398]
Hello,

> Affected version is v0.18.2

I have encountered an issue where the logo I use was showing twice, see example.
![image](https://github.com/user-attachments/assets/feb41683-204f-4d6f-a6f4-346cffaa180d)

Setting up a fresh and clean repo I didn't see the issue but it's still there, both icons are visible but the background hides one of them.
![image](https://github.com/user-attachments/assets/3de757c0-bcbf-4219-852b-aa7b1f7a359e)
![image](https://github.com/user-attachments/assets/7f4a65fa-0baa-4fb8-97b5-884f392e1856)

**Comment by dan-lee** [comment]
Oh, that must've happened when we switched to `next-themes`. Thanks for the report, will take a look.

**Comment by dan-lee** [comment]
Should be fixed in https://github.com/zuplo/zudoku/releases/tag/v0.18.3
