### ISSUE TITLE
Ctrl-C doesn't terminate the local server 

### ISSUE THREAD

**Issue by vazexqi** [zuplo/zudoku#82]
<img width="1334" alt="Screenshot 2024-08-30 at 10 17 45 AM" src="https://github.com/user-attachments/assets/b81c01fa-d0aa-4d3b-921b-9621bb088e7f">

I don't have full repro steps but I do notice that sometimes I end up in this odd state and you have to launch the process explorer to force kill the npm process.

**Comment by dan-lee** [comment]
Might be fixed along the way, didn't see this for a long time
